// <auto-generated />
using Kias_Kar_Kompany.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kias_Kar_Kompany.Migrations
{
    [DbContext(typeof(Kias_Kar_KompanyContext))]
    [Migration("20260408092911_SecondCommit")]
    partial class SecondCommit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kias_Kar_Kompany.Models.Manufacturer", b =>
                {
                    b.Property<int>("Manufacturerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Manufacturerid"));

                    b.Property<string>("Manufacturer_Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Manufacturerid");

                    b.ToTable("Manufacturer");
                });

            modelBuilder.Entity("Kias_Kar_Kompany.Models.Owner", b =>
                {
                    b.Property<int>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OwnerId"));

                    b.Property<string>("OwnerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.HasKey("OwnerId");

                    b.ToTable("Owner");
                });

            modelBuilder.Entity("Kias_Kar_Kompany.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<int?>("Manufacturerid")
                        .HasColumnType("int");

                    b.Property<int?>("Ownerid")
                        .HasColumnType("int");

                    b.Property<string>("VehicleImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehiclePrice")
                        .HasColumnType("int");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleId");

                    b.HasIndex("Manufacturerid");

                    b.HasIndex("Ownerid");

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("Kias_Kar_Kompany.Models.Vehicle", b =>
                {
                    b.HasOne("Kias_Kar_Kompany.Models.Manufacturer", "Manufacturer")
                        .WithMany("Vehicles")
                        .HasForeignKey("Manufacturerid");

                    b.HasOne("Kias_Kar_Kompany.Models.Owner", "Owner")
                        .WithMany("Vehicles")
                        .HasForeignKey("Ownerid");

                    b.Navigation("Manufacturer");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Kias_Kar_Kompany.Models.Manufacturer", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Kias_Kar_Kompany.Models.Owner", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
